[2024-06-23T12:28:39.487+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T12:28:39.502+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_4.create_table scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-23T12:28:39.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_4.create_table scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-23T12:28:39.508+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-23T12:28:39.517+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-06-23 00:00:00+00:00
[2024-06-23T12:28:39.521+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=785) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T12:28:39.522+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_table_4', 'create_table', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpb592dfxu']
[2024-06-23T12:28:39.522+0000] {standard_task_runner.py:63} INFO - Started process 786 to run task
[2024-06-23T12:28:39.523+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask create_table
[2024-06-23T12:28:39.558+0000] {task_command.py:426} INFO - Running <TaskInstance: create_table_4.create_table scheduled__2024-06-23T00:00:00+00:00 [running]> on host b6c62b670b43
[2024-06-23T12:28:39.622+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_table_4' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-23T12:28:39.623+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T12:28:39.630+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS my_table (id SERIAL PRIMARY KEY, name VARCHAR(50));
[2024-06-23T12:28:39.637+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-06-23T12:28:39.643+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-06-23T12:28:39.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T12:28:39.644+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 411, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-06-23T12:28:39.651+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=create_table_4, task_id=create_table, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240623T122839, end_date=20240623T122839
[2024-06-23T12:28:39.659+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task create_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 786)
[2024-06-23T12:28:39.696+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T12:28:39.703+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-23T12:28:39.712+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T12:28:39.715+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
