[2024-06-23T12:13:24.733+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-23T12:13:24.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table.create_table scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-23T12:13:24.767+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table.create_table scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-23T12:13:24.768+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-23T12:13:24.787+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-06-23 00:00:00+00:00
[2024-06-23T12:13:24.794+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-23T12:13:24.796+0000] {standard_task_runner.py:63} INFO - Started process 230 to run task
[2024-06-23T12:13:24.796+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'create_table', 'create_table', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpuczer4dr']
[2024-06-23T12:13:24.797+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask create_table
[2024-06-23T12:13:24.855+0000] {task_command.py:426} INFO - Running <TaskInstance: create_table.create_table scheduled__2024-06-23T00:00:00+00:00 [running]> on host b6c62b670b43
[2024-06-23T12:13:24.920+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_table' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-23T12:13:24.921+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-23T12:13:24.938+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS my_table (id SERIAL PRIMARY KEY, name VARCHAR(50));
[2024-06-23T12:13:24.945+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-23T12:13:24.951+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres` isn't defined
[2024-06-23T12:13:24.955+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=create_table, task_id=create_table, run_id=scheduled__2024-06-23T00:00:00+00:00, execution_date=20240623T000000, start_date=20240623T121324, end_date=20240623T121324
[2024-06-23T12:13:24.965+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task create_table (The conn_id `postgres` isn't defined; 230)
[2024-06-23T12:13:24.971+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-23T12:13:24.979+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-06-23T12:13:24.987+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-23T12:13:24.990+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
