[2024-07-08T07:12:01.689+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T07:12:01.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_v68.create_experiment scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T07:12:01.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_v68.create_experiment scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T07:12:01.706+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T07:12:01.716+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_experiment> on 2024-07-07 00:00:00+00:00
[2024-07-08T07:12:01.723+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T07:12:01.724+0000] {standard_task_runner.py:63} INFO - Started process 2688 to run task
[2024-07-08T07:12:01.724+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'model_training_v68', 'create_experiment', 'scheduled__2024-07-07T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/model_training.py', '--cfg-path', '/tmp/tmpxmfrhun6']
[2024-07-08T07:12:01.726+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask create_experiment
[2024-07-08T07:12:01.759+0000] {task_command.py:426} INFO - Running <TaskInstance: model_training_v68.create_experiment scheduled__2024-07-07T00:00:00+00:00 [running]> on host 999fa8207f52
[2024-07-08T07:12:01.813+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='model_training_v68' AIRFLOW_CTX_TASK_ID='create_experiment' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T00:00:00+00:00'
[2024-07-08T07:12:01.813+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T07:12:01.890+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:01 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 0.1 seconds
[2024-07-08T07:12:01.991+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:01 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 0.3 seconds
[2024-07-08T07:12:02.293+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:02 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 0.7 seconds
[2024-07-08T07:12:02.994+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:02 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 1.5 seconds
[2024-07-08T07:12:04.495+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:04 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 3.1 seconds
[2024-07-08T07:12:07.597+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:07 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 6.3 seconds
[2024-07-08T07:12:13.898+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:13 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 12.7 seconds
[2024-07-08T07:12:26.598+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:26 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 25.5 seconds
[2024-07-08T07:12:52.099+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:12:52 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 51.1 seconds
[2024-07-08T07:13:43.198+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:13:43 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 102.3 seconds
[2024-07-08T07:15:25.500+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:15:25 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 204.7 seconds
[2024-07-08T07:18:50.195+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:18:50 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 409.5 seconds
