[2024-07-08T06:55:08.811+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T06:55:08.822+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_training_v66.create_experiment scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T06:55:08.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_training_v66.create_experiment scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-08T06:55:08.827+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T06:55:08.836+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_experiment> on 2024-07-07 00:00:00+00:00
[2024-07-08T06:55:08.846+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T06:55:08.847+0000] {standard_task_runner.py:63} INFO - Started process 259 to run task
[2024-07-08T06:55:08.847+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'model_training_v66', 'create_experiment', 'scheduled__2024-07-07T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/model_training.py', '--cfg-path', '/tmp/tmpvbmbr_2n']
[2024-07-08T06:55:08.848+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask create_experiment
[2024-07-08T06:55:08.882+0000] {task_command.py:426} INFO - Running <TaskInstance: model_training_v66.create_experiment scheduled__2024-07-07T00:00:00+00:00 [running]> on host 999fa8207f52
[2024-07-08T06:55:08.941+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='model_training_v66' AIRFLOW_CTX_TASK_ID='create_experiment' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T00:00:00+00:00'
[2024-07-08T06:55:08.942+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T06:55:09.033+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:09 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 0.1 seconds
[2024-07-08T06:55:09.134+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:09 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 0.3 seconds
[2024-07-08T06:55:09.436+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:09 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 0.7 seconds
[2024-07-08T06:55:10.137+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:10 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 1.5 seconds
[2024-07-08T06:55:11.639+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:11 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 3.1 seconds
[2024-07-08T06:55:14.741+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:14 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 6.3 seconds
[2024-07-08T06:55:21.042+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:21 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 12.7 seconds
[2024-07-08T06:55:33.742+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:33 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 25.5 seconds
[2024-07-08T06:55:59.242+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:55:59 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 51.1 seconds
[2024-07-08T06:56:50.343+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:56:50 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 102.3 seconds
[2024-07-08T06:58:32.638+0000] {logging_mixin.py:188} WARNING - 2024/07/08 06:58:32 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 204.7 seconds
[2024-07-08T07:01:57.330+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:01:57 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 409.5 seconds
[2024-07-08T07:08:46.813+0000] {logging_mixin.py:188} WARNING - 2024/07/08 07:08:46 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
Operation will be retried in 819.1 seconds
